export {
  PivxClient,
  RpcError,
  AuthError,
  MalformedResponseError,
  ResponseTooLargeError,
  TransportError,
  type PivxClientOptions,
} from './client.js';
export { ShieldWatcher, watchViewingKey, type ShieldWatcherOptions } from './shield.js';
export {
  ZmqSubscriber,
  parseZmqFrame,
  ZmqError,
  TOPIC_HASHBLOCK,
  TOPIC_HASHTX,
  TOPIC_RAWBLOCK,
  TOPIC_RAWTX,
  type ZmqEvent,
} from './zmq.js';
export type {
  ShieldNote,
  ReceivedShieldNote,
  ShieldRecipient,
  ShieldSendSource,
  ShieldTxView,
  BlockchainInfo,
  WalletInfo,
  Unspent,
  BlockHeader,
  ChainTip,
  ScriptPubKey,
  TxOut,
  TxVin,
  TxVout,
  DecodedTransaction,
  TxInput,
  PrevTx,
  SignError,
  SignRawTransactionResult,
  WalletTransaction,
  ListSinceBlock,
  MasternodeCount,
  TransactionInfo,
  ValidateAddress,
  NetworkEntry,
  LocalAddress,
  NetworkInfo,
  PeerInfo,
  MempoolInfo,
  MempoolEntry,
  SupplyInfo,
  BlockIndexStats,
  MiningInfo,
  EstimateSmartFee,
  BudgetProposal,
  BudgetProjection,
  StakingStatus,
  StakingAddress,
} from './types.js';
