export { PivxClient, RpcError, AuthError, type PivxClientOptions } from './client.js';
export { ShieldWatcher, watchViewingKey, type ShieldWatcherOptions } from './shield.js';
export type {
  ShieldNote,
  ReceivedShieldNote,
  ShieldRecipient,
  ShieldSendSource,
  ShieldTxView,
  BlockchainInfo,
  WalletInfo,
  Unspent,
  BlockHeader,
  ChainTip,
  ScriptPubKey,
  TxOut,
  TxVin,
  TxVout,
  DecodedTransaction,
  TxInput,
  PrevTx,
  SignError,
  SignRawTransactionResult,
  WalletTransaction,
  ListSinceBlock,
  TransactionInfo,
  ValidateAddress,
} from './types.js';
